version: '3.1'

services:

  wordpress:
    image: wordpress:6.2.1-apache
    depends_on:
      - db
    restart: always
    ports:
      - "${PORT_WP:?}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER:?}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:?}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:?}
    volumes:
      - "${VOLUME_PATH_FOR_WP:?}:/var/www/html"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "${PORT_MYSQL:?}:3306"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:?}
      MYSQL_USER: ${MYSQL_USER:?}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "${VOLUME_PATH_FOR_DB:?}:/var/lib/mysql"
